### ISSUE TITLE
Rename Shutdown.icns to ShutDown.icns

### ISSUE THREAD

**Issue by lucaszischka** [blackosx/BsxM1#1]
First of all, thank you for the beautiful theme.

Now to my problem. I’m using vault and it didn’t lemme boot without renaming Shutdown.icns to ShutDown.icns. I’m using OpenCore version 0.7.1. After the rename and regenerating vault data it worked just fine. 👍

Greetings Lucas

**Comment by blackosx** [comment]
Thanks for the spot!
Fixed [9bc9a5](https://github.com/blackosx/BsxM1/commit/9bc9a5db93b390e29b2d0cd458a2e2e8dc90e06e)
