### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by kokowski** [blackosx/BsxM1#2]
Is ist possible to provide the selected.icns in just the blue shade of the existing one?

Thank you very much for all your work.

**Comment by kokowski** [comment]
Ok, tried it on my own. Even though I'm not that much of an image editor, but i think it's ok
![26172632](https://user-images.githubusercontent.com/57768825/165362028-f97ad8fc-e35d-486f-98f7-c950d221963d.png)
.

**Comment by blackosx** [comment]
Apologies for any delay but I've been away.

Well done for attempting this yourself. It's a good suggestion and I have gone ahead and created four alternative Selected icons each based on the colour of the original, so orange, blue, red and purple.

See commit [#0b5aae](https://github.com/blackosx/BsxM1/commit/0b5aae635eece3c8c906445a56749aee93fa073e)

Thanks
